### ISSUE TITLE
Chunk reloading

### ISSUE THREAD

**Issue by Seniorendi** [MarkusBordihn/BOs-Adaptive-Performance-Tweaks#1]
First, nice performance mods. Quite improves the server performance.

**Is your feature request related to a problem? Please describe.**
Hey,
when the server adjusts the load of the server (e.g. from LOW to NORMAL or NORMAL to Low), it reloads the clients chunks(Which is understandable). Which is quite annoying sometimes.

**Describe the solution you'd like**
A config key to disable the client reloading of the chunks. So players would need to reload their chunks manually.

**Describe alternatives you've considered**
A command to reload the chunks would be a good alternative.

**Comment by MarkusBordihn** [comment]
Thanks a lot for the report. Unfortunately this by design as soon the "viewdistance" gets adjusted.
You can mitigate the effect by using a higher minViewDistance or mods which avoid the "unloading" of chunks.

There is already a great mod which covers this issue called "Farsight", see:
- https://www.curseforge.com/minecraft/mc-mods/farsight

I will update the mod page to make it clear that farsight is recommend.
