### ISSUE TITLE
Issues with chunk loading

### ISSUE THREAD

**Issue by ItsDustyR6** [MarkusBordihn/BOs-Adaptive-Performance-Tweaks#2]
So I added most of your mods to my better minecraft pack since we have a few people on it. Just figured it would help optimize things which it did but some chunks just will not load. I'll run around and get to "the edge of the world" if you want to call it that. Basically ill hit a chunk that will not render at all. Sometimes chunks around it will load then unload. The only way to get these chunks to load is to disconnect and reconnect which only fixes the issue on the clients end. Using the debug reload doesn't work. Any thoughts or suggestions?

**Comment by MarkusBordihn** [comment]
Thanks for the report, but unfortunately my mods are not touching the client chunk loading or render chunk loading logic in any way.
The player module adjusts the view-distance, but this is done over the standard internal functions on the server side only.
You can disable this feature over the config file, but normally this has no effect on such chunk issues.

I saw this issue several time myself and it is mostly related to Optifine and other similar mods, which performing parallel processing of chunk loading like:
![image](https://user-images.githubusercontent.com/12183293/153963990-cdfbfe9a-a536-4acb-8731-35cba9ab2127.png)

This means it's an client related issue caused by some mods which modifying the the chunk loading on the client side.
Because my mods are server-side only, there is not really any relation to such client side chunk loading issues.

If you are using Optifine or something similar you should check if you can disable parallel chunk loading to avoid such issues or using other mods which force a full chunk reload on the client from time to time.

**Comment by ItsDustyR6** [comment]
great thanks. i turned it off in the config and it corrected the issue. i assume it was just a mod conflict
