### ISSUE TITLE
How about a way for users to upload/send mods to a database

### ISSUE THREAD

**Issue by Foxydapirate12** [MarkusBordihn/BOs-Adaptive-Performance-Tweaks#21]
**Is your feature request related to a problem? Please describe.**
I've noticed that quite a few mods fly under the radar and aren't picked up as clientsided for obvious reasons such as there being so many mods to manually label, so I've got an idea for a solution to help with labelling mods with which side they're meant for.

**Describe the solution you'd like**
How about a way for users to upload/send mods to a database so that they can be labelled as either clientside or serverside by the uploader, and be reviewed by a trusted person to ensure the label are correct and not trolls. And then added to Adaptive Performance Tweaks: Mods.

**Describe alternatives you've considered**
You could also try setting up something that could scan modrinth for which side they're meant for.

**Additional context**
![Mod sides](https://user-images.githubusercontent.com/101042481/185560684-92797eb0-fa90-4e35-ae5b-38e7a4184c51.jpg)

**Comment by MarkusBordihn** [comment]
Thanks a lot for the feedback. Unfortunately Modrinth is a great database, but is not providing the needed details like the mod filename to use the data directly.

I will do some adjustments so that the database is just a text file, which could be easily updated if needed.
Furthermore I will test some semi-automatic ways to get a better list, but as you already mentioned in most of the cases it's an manually process to make sure everything works as expected.

**Comment by MarkusBordihn** [comment]
Update the list and added a configuration file which could be easily adjusted.

https://github.com/MarkusBordihn/BOs-Adaptive-Performance-Tweaks/commit/8b294ee63d90db9c44e0d8a73e5b521f05925b36
