### ISSUE TITLE
1.19.2 Forge 'Spawn' Module #Tag support

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [MarkusBordihn/BOs-Adaptive-Performance-Tweaks#24]
**Is your feature request related to a problem? Please describe.**
Pokecube mobs flicker in and out of existence.

**Describe the solution you'd like**
![goKYdFU 1](https://user-images.githubusercontent.com/10351221/192050969-3411238a-4648-43e9-9521-14e768313ef0.png)

**Describe alternatives you've considered**
Removing the mod.

**Additional context**
None at this time I will watch this topic.

**Comment by MarkusBordihn** [comment]
Thanks for the report. Could you please explain the issue more in detail ?

The mod is only "blocking" new spawn events, but is not removing existing mobs from the world or so.
So I'm not really understand the "Pokecube mobs flicker in and out of existence.", does this happen if you try to use an catch item or so ?

But happy to take a look into allowing tags additional to entities ids.

**Comment by P3rf3ctXZer0** [comment]
Error I actually have no idea how to describe it they keep popping in and out of existence but it seems more like flashing placeholders. @thutmose I wish you would do the talking as I have no idea how to express it. 

At any rate if you want I can show you some video footage.

**Comment by MarkusBordihn** [comment]
Thanks a lot for the video, this is already very helpful.
I think I have an idea what is causing this and will try to reproduce the issue to working on a fix.

**Comment by P3rf3ctXZer0** [comment]
I need to report it might not be the spawn module ... either way if it helps with testing I used the full adaptive tweaks bundle.

**Comment by Thutmose** [comment]
I suspect that this is due to pokecube spawning in the pokemobs based on the density of existing pokemobs in the area, so if the spawn events get cancelled, it will try again at another spawn pass relatively quickly.

This is due to the common cause of the mobs disappearing rapidly is when players are trying to grind levels of their mobs, so they killed them nearly as soon as they spawned, so another set spawns.

There are however order 1e3 of these mobs, so adding each one to a config option is not really convenient. They are all in a single entity type tag however, so supporting that in the configs would be helpful.

**Comment by MarkusBordihn** [comment]
This should be fixed in the latest version.

Because Pokecube AIO has their own spawn control, it makes no sense for the mod to perform any kind of optimization or limitation of spawn entities.

This mean the mod will automatically ignore all spawn events from the mod id `pokecube:` so that it should not cause any visual or spawning issues.

**Comment by P3rf3ctXZer0** [comment]
I will test it now thank you.

**Comment by P3rf3ctXZer0** [comment]
Also is this backported to 1.18.2?

**Comment by MarkusBordihn** [comment]
Yes, should be live in 1.18.2 and 1.19.2.
