### ISSUE TITLE
1.19.2 Spawn Module Killed all my Productive Bees

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [MarkusBordihn/BOs-Adaptive-Performance-Tweaks#25]
**Describe the bug**

**To Reproduce**

- Install Productive bees
- Make a large scale colony
- Teleport
- All bees gone.

**Expected behavior**

- My 46 bees should still be buzzing

**Screenshots**

![2022-10-02_09 26 04](https://user-images.githubusercontent.com/10351221/193459264-cdd050af-af34-46a3-84bf-af22c3459cfc.png)

**Debugging**
Before reporting a issue please use `/aptweaks debug true` to enable debugging and check if there is anything relevant in the debug.log file.

**Is the issue happening in combination with other mods? (If yes, please provide a full list)**

- productivebees-1.19.2-0.10.2.0
- adaptive_performance_tweaks_spawn_1.19.2-6.1.0

**Additional context**

Everything is also chunk loaded using forge chunkloader but is set to not tick if I am offline.

**Comment by P3rf3ctXZer0** [comment]
Sadness also affect regular bees.

**Comment by MarkusBordihn** [comment]
Thanks for the report. Normally the mod is not "killing" any existing entities and is only optimizing entities which are spawning / re-spawning.
It could be that this is related to the chunk-loader, but I will test this more in detail.

Because I never used the productive bees mod so far, could you let me know what is normally the numbers of bees for a large scale colony so that I spawn enough bees during my tests ?

**Comment by P3rf3ctXZer0** [comment]
Um 5 bees per hive base but I have seen ridiculous numbers. You might want to watch some pro builders as I am a scrub.

**Comment by MarkusBordihn** [comment]
Thanks for the feedback. I released a fix, which will ignore all bees with a hive.
The productive bees extending the normal bees so they should be automatically fixed as well.

Please reopen the issue report if you still see any issues with the version https://www.curseforge.com/minecraft/mc-mods/adaptive-performance-tweaks-core/files/4016548 or higher.

**Comment by P3rf3ctXZer0** [comment]
thanks again :D
