### ISSUE TITLE
Rubidium overrides APTweaks view distance rules

### ISSUE THREAD

**Issue by freopt** [MarkusBordihn/BOs-Adaptive-Performance-Tweaks#3]
**Describe the bug**
If Rubidium (forge sodium port) is installed, APTweaks: Player view distance configs don't do anything and the render distance is always what is set in the Rubidium video settings. Seemingly doesn't happen with simulation distance, at least when using /aptweaks.

**To Reproduce**
Install latest version of aptweaks player and rubidium on 1.18.2

**Expected behavior**
APTweaks to have priority in render distance settings. If this can't be fixed on your side I'll report to rubidium

**Comment by MarkusBordihn** [comment]
Thanks a lot for the report and I checked their source code more in detail to confirm the issue. 
Relevant part:
https://github.com/Asek3/Rubidium/blob/f7e9885d4c266f2d218fa3aa120285ae7d3362e6/src/main/java/me/jellysquid/mods/sodium/client/render/chunk/RenderSectionManager.java#L455

Here you can see that they are performing a client side filtering, which means even if the server supports a higher view distance the client basically don't care, if it is above the client config.

Because this happens on the client, there is nothing I could do on the server side.
This filtering will cause issue with other mods which relies on the view distance / unfiltered entities.

I will add a warning to my mods to make sure, users are aware about this.

You can report the issue to rubidium, but the only way to fix this would be to allow dynamic updates of the view / render distances based on the current view distance on the server. 
Their currently implementation is static and requires are restart after a change to the view / render distance.
