### ISSUE TITLE
Frequent server crashes linked to `Accessing LegacyRandomSource from multiple threads` after recent APT update.

### ISSUE THREAD

**Issue by hazardoushazik** [MarkusBordihn/BOs-Adaptive-Performance-Tweaks#31]
**Describe the bug**
Frequent server crashes linked to `Accessing LegacyRandomSource from multiple threads` after recent APT update. Note that these server crashes did not occur in the last version of APT.

Now I'm not 100% sure the issue is with APT, its likely a compatibility issue. In terms of performance mods, my server is running APT, Performant, and Rubidium. There were many crashes tonight with the same error and I have attached them all.

I am reporting the crashes here since removing APT has removed all instances of the aforementioned error appearing on the server

**To Reproduce**
1. Add APT (all mods) to server
2. Start server.
3. Experience frequent crashes

**Expected behavior**
Should not crash (lol)

**Screenshots**

**Debugging**
Before reporting a issue please use `/aptweaks debug true` to enable debugging and check if there is anything relevant in the debug.log file.

**Is the issue happening in combination with other mods? (If yes, please provide a full list)**
Full mod-list included in crash-reports. I have not done an extensive analysis of the crashes to determine which combinations cause issues as removing APT resolved the crashes.

**Additional context**
It should be noted that there were multiple JIRA tickets (e.g. [MC-250008](https://bugs.mojang.com/browse/MC-250008), [MC-249933](https://bugs.mojang.com/browse/MC-249933)) submitted to Mojang for the same error that were remedied in 
22w15a prior to the last 1.19 release.

[crash-2022-12-05_21.14.08-server.txt](https://github.com/MarkusBordihn/BOs-Adaptive-Performance-Tweaks/files/10162940/crash-2022-12-05_21.14.08-server.txt)
[crash-2022-12-05_19.29.32-server.txt](https://github.com/MarkusBordihn/BOs-Adaptive-Performance-Tweaks/files/10162941/crash-2022-12-05_19.29.32-server.txt)
[crash-2022-12-05_19.11.54-server.txt](https://github.com/MarkusBordihn/BOs-Adaptive-Performance-Tweaks/files/10162942/crash-2022-12-05_19.11.54-server.txt)
[crash-2022-12-05_19.02.03-server.txt](https://github.com/MarkusBordihn/BOs-Adaptive-Performance-Tweaks/files/10162943/crash-2022-12-05_19.02.03-server.txt)
[crash-2022-12-05_18.07.56-server.txt](https://github.com/MarkusBordihn/BOs-Adaptive-Performance-Tweaks/files/10162944/crash-2022-12-05_18.07.56-server.txt)
[crash-2022-12-05_17.51.02-server.txt](https://github.com/MarkusBordihn/BOs-Adaptive-Performance-Tweaks/files/10162946/crash-2022-12-05_17.51.02-server.txt)
[crash-2022-12-05_21.24.58-server.txt](https://github.com/MarkusBordihn/BOs-Adaptive-Performance-Tweaks/files/10162947/crash-2022-12-05_21.24.58-server.txt)

**Comment by MarkusBordihn** [comment]
Thanks a lot for the report. Unfortunately I see no reference to this mod in the crash logs, which means it's very likely caused by one of the mods which modifying the core functionality (mixins.).

Adaptive Performance Tweaks is not using any mixins or core modding, which means if the crash is caused by this mod, it will be show up directly in the crash reports.

It seems that one of the mods overwrites the spawn logic, so you could disable the "adaptive_performance_tweaks_spawn" module to see if this fixes the issue.
In general you should not use mods with overlapping features, so if any other mod is optimization the spawn of mobs, there should be no other additional mod which doing something similar.

I will try to reproduce the issue on my test server just to be sure, but the issue is more related to one of the following mods instead:
`re:mixin,pl:accesstransformer:B,xf:fml:forgeendertech:coremod,re:classloading,pl:accesstransformer:B,xf:fml:forgeendertech:coremod,pl:mixin:APP:performant.mixins.json:world.ServerWorldBlockUpdateMixin,pl:mixin:APP:citadel.mixins.json:ServerLevelMixin,pl:mixin:APP:supplementaries-common.mixins.json:ServerLevelMixin,pl:mixin:APP:betterdeserttemples.mixins.json:ServerLevelMixin,pl:mixin:APP:blueprint.mixins.json:ServerLevelMixin,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:APP:performant.mixins.json:world.ServerWorldEntityDistMixin,pl:mixin:APP:performant.mixins.json:world.ServerWorldMixin,pl:mixin:APP:byg.mixins.json:common.world.MixinServerLevel,pl:mixin:APP:assets/sound_physics_remastered/sound_physics_remastered.mixins.json:ServerWorldMixin,pl:mixin:APP:create.mixins.json:accessor.ServerLevelAccessor,pl:mixin:A`

**Comment by MarkusBordihn** [comment]
Run a test over two days and was not able to reproduce the issue with my test mod pack.
![image](https://user-images.githubusercontent.com/12183293/207427523-f1d3c0a4-fe5f-4f4b-9942-f04487426ddc.png)

So its seems a specific Mixin issue with one of the installed mods.
As I mentioned you could try to disable the "spawn" module, so that there a no overlapping features from other mods.
