### ISSUE TITLE
[Question] Custom Spawn Rules

### ISSUE THREAD

**Issue by pewblaze** [MarkusBordihn/BOs-Adaptive-Performance-Tweaks#44]
Hi, sorry i dont have a bug, but a question. I hope its okay to ask like that ^^"

Im trying to add CustomSpawn Rules, but somehow it seems like im doing something wrong? 
Could you check the code if its the correct way or am i missing something/doing it wrong? ^^" Do i have to change the "custom" to a mod name?
Im running the command "/aptweaks spawnrules" and it doesnt show any of the mobs, so i assume they arent working at all.

Here are the files:

https://gist.github.com/pewblaze/c11e699319c5841a2c5a8cf71addc936

**Comment by MarkusBordihn** [comment]
Thanks for the feedback. No worries even if this is no bug, it's a feature request.

The mod is not automatically checking for new "config" files, so I need to add them manually for each mod.
But thanks for your details, I will add them with the next update so that they should work without any issues.

**Comment by pewblaze** [comment]
Ah i see, thanks for the information. :)
