### ISSUE TITLE
Slight increase in Entity TPS usage after update?

### ISSUE THREAD

**Issue by Reshy** [MarkusBordihn/BOs-Adaptive-Performance-Tweaks#48]
**Describe the bug**
After updating, I noticed most entities have between 5-10 us/t higher when using Observable.  Seems most noticeable with animals (tested specifically with chickens).  Could be due to other factors, but I tried to minimize those as much as I could, reusing the same world and testing the same mobs.  Some of the TPS is from other mods, but the only thing that changed between the two screen shots was the two updates.

**To Reproduce**
1. Place mobs as below using 
2. Run Observable in 30 sec mode.

**Expected behavior**
The update shouldn't be having a performance impact such as this.

**Screenshots**
![2023-05-29_02 33 47](https://github.com/MarkusBordihn/BOs-Adaptive-Performance-Tweaks/assets/2096384/738c3fb1-0603-4a1a-9315-4295019dff42)
![2023-05-29_02 11 01](https://github.com/MarkusBordihn/BOs-Adaptive-Performance-Tweaks/assets/2096384/7dfc8b5b-1da5-456b-9ae1-8371cd43c2a9)

**Debugging**
Didn't have this setup for the test, wasn't aware of it.

**Comment by MarkusBordihn** [comment]
Thanks for the report. In the last update I fixed an issue were mobs in the nether where over optimized.
With the fix it's expected that you get about 25% more vanilla nether mobs than before, which could have this impact, but only if the nether dimension is loaded or if you have nether mobs in the overworld.

I will run some performance profile to see if there is anything I overlooked, but it would be great if you could use [Spark](https://www.curseforge.com/minecraft/mc-mods/spark) or something like this to get a clear report about the usage of the single processes like: https://spark.lucko.me/H9Z9rLddg7

You just need to run `/spark profile start`, moving around the world for 1-5 minute or so and than using `/spark profile stop` to get the final report. (Don't use `/sparkc` because this is for the client side)

**Comment by Reshy** [comment]
I can try that, though I think the results may vary since hostile mobs aren't saved.

**Comment by Reshy** [comment]
Here's what I got, but I dunno how conclusive it is:

Before:
https://spark.lucko.me/aAlQe9bq88
![Before Update](https://github.com/MarkusBordihn/BOs-Adaptive-Performance-Tweaks/assets/2096384/3579e9f4-e107-4b61-ab74-96fcb6b00348)


After:  
https://spark.lucko.
![After Update](https://github.com/MarkusBordihn/BOs-Adaptive-Performance-Tweaks/assets/2096384/f20e365c-1dd9-4572-90c2-c84658abe78f)
me/h1QC8Qimp9

**Comment by MarkusBordihn** [comment]
Thanks for the details. I just added some smaller performance updates for some parts which show up on your profile.
Unfortunately besides of this I see not a lot of performance different for the core and items module your are using.
Because you are not using the "spawn" module, most of the changes from last update are not affecting you at all.
