### ISSUE TITLE
1.19.2 BUG HUGE SEVERE! Adaptive Peformance Tweaks - Completely Cripples Minecolonies in an extremely strange way. 

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [MarkusBordihn/BOs-Adaptive-Performance-Tweaks#54]
Not wasting more time please see google doc of entire discord convo with Minecolonies
https://docs.google.com/document/d/1YgFTYPTvs6HGJYAj-2LT63HQFIRPAxXTpL-hNBKmJ2c/edit?usp=sharing

If you do nothing with this report I will simply never use your mods again I spent 2 hours to come to this conclusion to the point where my Bipolar has taken over. I hope you consider joining Minecolonies discord to find a solution.

https://discord.minecolonies.com/

1.19.2 Forge 43.2.21
adaptive_performance_tweaks_core_1.19.2-6.9.1.jar
adaptive_performance_tweaks_gamerules_1.19.2-6.8.0.jar

**Comment by MarkusBordihn** [comment]
Thanks for the report. Unfortunately the shared doc nor the bug report provides any hint to reproduce the issue on my side.

# Could you confirm that you are only using the following two mods and nothing else like "items" or "spawn" ?
- adaptive_performance_tweaks_core_1.19.2-6.9.1.jar
- adaptive_performance_tweaks_gamerules_1.19.2-6.8.0.jar

## If yes, then it could not be really related to these mods. 

1. The "core" mod is only collecting and logging specific entities and item data but is not doing or changing anything else.
2. The "gamerules" mod is adjusting existing Minecraft rule like if you manually using the "/gamerule ... " command. If adjusting any of these game rules results in a bug it's more a general bug / issue with the game instead of this mod.

In fact there is even an additional check for "Minecolonies" to make sure that the "MAX_ENTITY_CRAMMING"  for the "gamerules" mod is not going below a specific value (default config=16).
See: https://github.com/MarkusBordihn/BOs-Adaptive-Performance-Tweaks/blob/504e90d28c648cad9559d6704088f9d40aba0384/gamerules/src/main/java/de/markusbordihn/adaptiveperformancetweaksgamerules/gamerules/GameRuleManager.java#L295C1-L305C6

This means if you are only using these two mods, try to "disable" the "Entity Cramming" or set the "minEntityCrammingMineColonies" to 24 in the config file, which would be the default game setting.

## If no, it could be only related "spawn", but less to "items"

The spawn module is automatically ignoring all entities starting with "minecolonies", but if they are using other names for these kind of blocks they could be maybe wrongly "optimized"
See: https://github.com/MarkusBordihn/BOs-Adaptive-Performance-Tweaks/blob/504e90d28c648cad9559d6704088f9d40aba0384/core/src/main/java/de/markusbordihn/adaptiveperformancetweakscore/entity/CoreEntityManager.java#L469C4-L469C4

The items module is only checking for "ItemEntity" which such blocks should not be, but happy to add an default exclusion for "minecolonies" item entity to see if this was the main issue.
See: https://github.com/MarkusBordihn/BOs-Adaptive-Performance-Tweaks/blob/504e90d28c648cad9559d6704088f9d40aba0384/items/src/main/java/de/markusbordihn/adaptiveperformancetweaksitems/entity/ItemEntityManager.java#L153C1-L157C6

# Next steps

I understand it's hard to get to the bottom of such issues and I'm happy and willing to help.
But without a way to reproduce the issue on my side there is unfortunately not a lot I could do.

**Comment by P3rf3ctXZer0** [comment]
I think it is specifically related to tick syncing. The core claims in my logs it is changing tick delay based on load are you sure you checked your mod? I have hours of proof claimin it adjusts tick load ... I cannot be more clear with just this and mincolonies it breaks don't know how or why I recommend you contact raycoms as soon as possible as the dev is actively telling people not to use your mods.

It broke in their testing too.

I wish I knew code so I could myself find the offending issues since both your mod and Raycoms Minecolonies dev team have a source aviable but I am disabled and this drastically limits my impact with code.

Honestly you are wasting both of our times not contacting their team.

**Comment by MarkusBordihn** [comment]
I understand your concerns and the effort you've put into identifying the issue. However, without access to concrete evidence or a way to reproduce the problem, it's difficult for me to provide any assistance. 
As you mentioned, diagnosing and resolving issues requires specific information and reproducible steps to identify the root cause.

The core mod is not adjusting any ticking at all, it's just measure and record the load.
Because my mods are not using any core modding / mixing they are also technically not able to change something like the ticking.

You can easily check this, by searching for "accesstransformer.cfg", "mixin" and "coremod" and you will find no relevant results for something like this in the code base:
https://github.com/search?q=repo%3AMarkusBordihn%2FBOs-Adaptive-Performance-Tweaks%20accesstransformer.cfg&type=code

I'm here to help, but please keep in mind that I'm unable to investigate issues without proper evidence or a clear way to reproduce them. Also, please note that I'm assisting you voluntarily and without any compensation.

**If you can direct me to their testing, which provides clear evidence of my mod causing the issue, I'd be more than willing to thoroughly investigate the matter and reach out to them for further discussion.**
