### ISSUE TITLE
1.20.1 Bundle crashes without using APT Items and Gamerules

### ISSUE THREAD

**Issue by cobaltw** [MarkusBordihn/BOs-Adaptive-Performance-Tweaks#62]
Title. Crash log linked.
Similarly, trying to use any individual mods will result in it crashing due to not having the rest of the APTweak mods.
Using the core with all the individual mods installed makes it function properly.
[crash-2024-01-21_00.07.00-fml.txt](https://github.com/MarkusBordihn/BOs-Adaptive-Performance-Tweaks/files/14000233/crash-2024-01-21_00.07.00-fml.txt)

**Comment by MarkusBordihn** [comment]
Thanks for the report. It's expected that the bundle crashes (missing dependency), because the bundle expect that all mods are used.

If you only want to use specific modules / part, please  remove the bundle and install the `core` with any of the other modules you want to use.
See: https://github.com/MarkusBordihn/BOs-Adaptive-Performance-Tweaks/wiki/HowToUse#modules-%EF%B8%8F

**Comment by cobaltw** [comment]
Then, does the bundled version itself not actually do anything?

**Comment by MarkusBordihn** [comment]
Yep, the bundled version is a kind of empty mod with include all modules as requirements like:
https://github.com/MarkusBordihn/BOs-Adaptive-Performance-Tweaks/blob/b4cdc24897c2138055235014123f7ec59ce6ca26/bundle/build.gradle#L196C1-L200C63

It exists mostly for historical reasons, because the version 1.16.5 only exists as bundle and not as separate module.
So mod pack creator asked to have a single mod which includes all modules for 1.18.2 and higher.

**Comment by cobaltw** [comment]
This should probably be specified somewhere, as-is I assumed it was an alternative to having to have each individual mod. Unless I just missed that clarification somewhere?

**Comment by MarkusBordihn** [comment]
Related wiki: https://github.com/MarkusBordihn/BOs-Adaptive-Performance-Tweaks/wiki/HowToUse
