### ISSUE TITLE
TONS OF SQUIDS AND DOLPHINS

### ISSUE THREAD

**Issue by Faykie** [MarkusBordihn/BOs-Adaptive-Performance-Tweaks#63]
**Describe the bug**
a lot of squids and dolphins spawning, 1000 + 

what do i do?

**Comment by MarkusBordihn** [comment]
Please follow the troubleshooting guide to provide a debug.log.
See: https://github.com/MarkusBordihn/BOs-Adaptive-Performance-Tweaks/wiki/Troubleshooting

The `debug.log` should give more insights if they are naturally spawning and if they should be blocked.

In general the mod is blocking spawn events, but is normally not spawning mobs by itself.
This could be caused by other mods which are ignoring the standard spawn system or using their own system.
