### ISSUE TITLE
Crashed suddenly...

### ISSUE THREAD

**Issue by Ashenguard** [MarkusBordihn/BOs-Adaptive-Performance-Tweaks#71]
**Describe the bug**
Not sure how it happened as I was busy mining... But suddenly it crashed with this mod in the report.

**To Reproduce**
Happened suddenly... Not sure how... I was just mining

Here is the crash report
[crash-2024-08-21_19.38.41-server.txt](https://github.com/user-attachments/files/16695113/crash-2024-08-21_19.38.41-server.txt)
.

**Comment by MarkusBordihn** [comment]
Thanks for the report! It looks like the entity had already been created, which is why APTweaks couldn't stop it from spawning. 
This usually happens when a mod uses the highest priority to spawn entities.

I'll add an extra check to prevent issues like this from causing the game to crash. 
I really appreciate you sending the report and the crash log!

**Comment by EliasRipley** [comment]
Believe this issue occured on my server as well. Will be sure to slap on an extra log should I see it again.
